### ISSUE TITLE
Missing code parameter 

### ISSUE THREAD

**Issue by divanski** [pole-numerique/oasis-php-integration#2]
When I try to get access Token whit this code:

```
$oasis = Oasis::builder()
            ->setProviderConfig($this->providerConfiguration)
            ->setCache(new ApcCache())
            ->setCredentials($clientid, $clientsecret))
            ->setDefaultRedirectUri($redirect)
            ->build();
        list($authorizationRequestUri, $serializedState, $nonce) = $oasis
            ->initAuthorizationRequest()
            ->setScope(array('openid', 'email', 'profile'))
            ->setRedirectUri($redirect)
            ->setState('project.1.edit')
            ->buildUri();
        try {
            list($accessToken, $refreshToken, $idToken, $state) = $oasis
                ->initExchangeCodeForTokenRequest()
                ->setAuthorizationResponse($authorizationRequestUri)
                ->setRedirectUri($redirect)
                ->setExpectedState($serializedState)
                ->setExpectedNonce($nonce)
                ->execute();
        }
```

 I get the error message "Missing code parameter". 

Where I'm wrong?

**Comment by tbroyer** [comment]
From the README:

> Now you can redirect the user to this URI.

and then:

> After the user logged in and authorized your application (or not), he will be redirected to the redirect_uri provided in the Authorization request.
> 
> The result is conveyed in the query parameters.
> 
> Provide the query string of the actual uri to the API for processing it and get an access token in exchange (if the Authorization process was successful).

I invite you to carefully read the README and map each step to the corresponding step in http://doc.ozwillo.com/#s4-auth-code-flow

There's also an overview in http://doc.ozwillo.com/#s1-authorization to get started in understanding the concepts and flow.

**Comment by divanski** [comment]
Thomas, I don't like your answer!

From the README: 
```
// Optional if default 'redirect_uri'
// Will override the default one if provided
->setRedirectUri('https://app2.example.com/another-redirect')
```

For me redirect_url is the same.

After the user logged in and authorized he is redirected to:
https://blabla.com/index.php/component/oasisclient/check?state=eyJzdGF0ZSI6bnVsbCwicmFuZG9tIjoiWkFcLzBZQ3AzRHEwWHZcL1l3aDQ0TjhiY21CcnpcL3ZoWnA1ZHlmVnNsNkFFND0ifQ%3D%3D&code=eyJpZCI6IjkyNThkYTVjLTI3YzUtNDA5ZS1iYWVhLTU3ZmUzYTIwYmZhMC9RY25hOUhPUFdYUmNoSndnOTdLQVpnIiwiaWF0IjoxNDMxNDE3MDY1NTM3LCJleHAiOjE0MzE0MTcxMjU1Mzd9

And as I see "code" exists in the url, but the function
```
-> initExchangeCodeForTokenRequest () 
```
does not detect code.

I asked where I'm wrong? and wrong isn't in redirect_uri.

And if you think I have not read the documentation, how do you think Altourism work now?

In the future I will ask you to answer a specific question.
I think that both tasks will run better and faster.

**Comment by tbroyer** [comment]
Sorry. From the code snippet you gave in the original report, I thought you were calling `initExchangeCodeForTokenRequest` just after the call to `initAuthorizationRequest` without redirecting to the `$authorizationRequestUri` in between.

So, your issue here is:

``` php
                ->setAuthorizationResponse($authorizationRequestUri)
```

From the README:

> ``` php
>     // The query string of the actual uri used by
>     // the Authorization endpoint to redirect the user.
>     // An array corresponding to the query string can also
>     // be provided instead of the query string.
>     ->setAuthorizationResponse($queryString)
> ```

You should pass `$_SERVER['QUERY_STRING']` or `$_GET` or `new HttpQueryString()->toArray()` or something similar; i.e. pass the `code`  (or `error`) and `state` parameters you received to the object.

As a rule of thumbs, the library never operates on _globals_, all inputs have to be explicitly given.

**Comment by divanski** [comment]
Thanks,  Now I already know where my mistake
